services:
  mayobox_web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_BASE_SERVER_URL=http://localhost:4000
    container_name: mayobox_web
    ports:
      - "3000:3000"
    restart: unless-stopped
